version: '3.3'

services:
  #service 1: definition of mysql database
  trade-db:
    image: mysql:latest
    container_name: trade-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3310:3306"
    restart: always

  #service 2: definition of your spring-boot app
  trade-backend:                               #it is just a name, which will be used only in this file.
    image: trade-backend                                #name of the image after dockerfile executes
    container_name: trade-backend                   #name of the container created from docker image
    build:
      context: .                                #docker file path (. means root directory)
      dockerfile: Dockerfile                    #docker file name
    ports:
      - "8080:8080"                             #docker container port with your os port
    restart: always

    depends_on:                                 #define dependencies of this app
      - trade-db                               #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      DATASOURCE_URL: jdbc:mysql://trade-db:3306/trade?createDatabaseIfNotExist=true
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: password
      SECRET_KEY: secret
      MAIL_USERNAME: validatebro@gmail.com
      MAIL_PASSWORD: Spring1800
      API_KEY: pk_1df1eaf705b14ae5806810ffed975b00
